export const provinceData = [
  "Punjab",
  "Sindh",
  "Khyber Pakhtunkhwa",
  "Balochistan",
];

export const cityData = {
  Punjab: [
    "Attock",
    "Bahawalpur",
    "Bahawalpur",
    "Chiniot",
    "Dera Ghazi Khan",
    "Faisalabad",
    "Gujranwala",
    "Gujrat",
    "Jhang",
    "Kasur",
    "Khanewal",
    "Khanpur",
    "Lahore",
    "Layyah",
    "Lodhran",
    "Multan",
    "Muzaffargarh",
    "Narowal",
    "Nankana Sahib",
    "Okara",
    "Pakpattan",
    "Rahim Yar Khan",
    "Rajanpur",
    "Sahiwal",
    "Sargodha",
    "Sheikhupura",
    "Toba Tek Singh",
    "Vehari",
    "Wazirabad",
    "Zafarwal",
  ],
  Sindh: [
    "Jacobabad",
    "Kashmore",
    "Larkano",
    "Kamber Shahdadkot",
    "Shikarpur",
    "Ghotki",
    "Sukkur",
    "Khairpur",
    "Naushero Feroz",
    "Shaheed Benazirabad",
    "Sanghar",
    "Mirpurkhas",
    "Umerkot",
    "Tharparkar",
    "Dadu",
    "Jamshoro",
    "Matiari",
    "Hyderabad",
    "Tando Muhammad Khan",
    "Tando Allahyar",
    "Badin",
    "Sujawal",
    "Thatta",
    "Karachi",
  ],
  KPK: [
    "Peshawar",
    "Abbottabad",
    "Mardan",
    "Swat",
    "Dera Ismail Khan",
    "Bannu",
    "Kohat",
    "Nowshera",
    "Charsadda",
    "Mansehra",
    "Shangla",
    "Batagram",
    "Lower Dir",
    "Upper Dir",
    "Hangu",
    "Karak",
    "Lakki Marwat",
    "Tank",
    "Dera Ismail Khan",
    "Peshawar",
    "Chitral",
  ],
  Balochistan: [
    "Quetta",
    "Kalat",
    "Sibi",
    "Khuzdar",
    "Turbat",
    "Gwadar",
    "Zhob",
    "Loralai",
    "Nushki",
    "Panjgur",
    "Dera Bugti",
    "Jaffarabad",
    "Awaran",
    "Lasbela",
    "Bolān",
    "Chaman",
    "Turbat",
    "Mastung",
    "Nushki",
    "Sibi",
  ],
};

export const districtData = {
  Attock: ["Attock", "Hazro", "Jand", "Pindi Gheb", "Hasan Abdal"],
  Bahawalpur: [
    "Bahawalpur City",
    "Bahawalpur Saddar",
    "Hasilpur",
    "Ahmadpur East",
    "Yazman",
  ],
  Chiniot: ["Chiniot", "Bhowana", "Lalian"],
  Dera_Ghazi_Khan: ["Dera Ghazi Khan", "Taunsa", "Kot Chutta"],
  Faisalabad: [
    "Faisalabad City",
    "Jaranwala",
    "Samundri",
    "Tandlianwala",
    "Chak Jhumra",
  ],
  Gujranwala: ["Gujranwala City", "Kamoke", "Nowshera Virkan", "Wazirabad"],
  Gujrat: ["Gujrat City", "Kharian", "Sara-e-Alamgir"],
  Jhang: ["Jhang City", "Shorkot", "Ahmadpur Sial", "18-Hazari"],
  Kasur: ["Kasur City", "Chunian", "Pattoki", "Kot Radha Kishan"],
  Khanewal: ["Khanewal City", "Mian Channu", "Kabirwala", "Jahanian"],
  Khanpur: ["Khanpur City", "Kot Mithan"],
  Lahore: ["Lahore City", "Raiwind", "Model Town", "Shalimar"],
  Layyah: ["Layyah City", "Karor Lal Esan", "Chowk Azam"],
  Lodhran: ["Lodhran City", "Dunyapur", "Kahror Pakka"],
  Multan: ["Multan City", "Shujabad", "Jalalpur Pirwala"],
  Muzaffargarh: ["Muzaffargarh City", "Kot Addu", "Jatoi", "Alipur"],
  Narowal: ["Narowal City", "Shakargarh", "Zafarwal"],
  Nankana_Sahib: ["Nankana Sahib City", "Sangla Hill", "Shahkot"],
  Okara: ["Okara City", "Depalpur", "Renala Khurd"],
  Pakpattan: ["Pakpattan City", "Arifwala"],
  Rahim_Yar_Khan: ["Rahim Yar Khan City", "Khanpur", "Liaquatpur", "Sadiqabad"],
  Rajanpur: ["Rajanpur City", "Jampur", "Rojhan"],
  Sahiwal: ["Sahiwal City", "Chichawatni"],
  Sargodha: ["Sargodha City", "Bhalwal", "Shahpur", "Sahiwal", "Sillanwali"],
  Sheikhupura: [
    "Sheikhupura City",
    "Ferozewala",
    "Safdarabad",
    "Sharqpur",
    "Sharaqpur",
  ],
  Toba_Tek_Singh: ["Toba Tek Singh City", "Gojra", "Kamalia", "Pir Mahal"],
  Vehari: ["Vehari City", "Burewala", "Mailsi"],
  Wazirabad: ["Wazirabad City", "Sodhra"],
  Zafarwal: ["Zafarwal City"],

  Quetta: ["Quetta City", "Dasht", "Pishin", "Hanna Urak"],
  Kalat: ["Kalat City", "Surab", "Mangochar"],
  Sibi: ["Sibi City", "Lehri", "Bara G", "Talli"],
  Khuzdar: ["Khuzdar City", "Wadh", "Nal", "Mula", "Ornach"],
  Turbat: ["Turbat City", "Dasht", "Buleida"],
  Gwadar: ["Gwadar City", "Pasni", "Ormara", "Jiwani"],
  Zhob: ["Zhob City", "Sherani", "Muslim Bagh", "Qamar Din Karez"],
  Loralai: ["Loralai City", "Duki", "Bori"],
  Nushki: ["Nushki City", "Dalbandin", "Mashkhel"],
  Panjgur: ["Panjgur City", "Gichk", "Paroom", "Tasp"],
  Dera_Bugti: ["Dera Bugti City", "Sui", "Pirkoh"],
  Jaffarabad: ["Jaffarabad City", "Usta Muhammad", "Sohbatpur"],
  Awaran: ["Awaran City", "Jhal Jhao"],
  Lasbela: ["Lasbela City", "Uthal", "Dureji", "Hub"],
  Bolan: ["Bolan City", "Dhadar", "Mach", "Bibi Nani"],
  Chaman: ["Chaman City", "Qila Abdullah", "Gulistan"],
  Mastung: ["Mastung City", "Dasht", "Khad Kocha"],

  Peshawar: ["Peshawar City", "Badaber", "Mattani"],
  Abbottabad: ["Abbottabad City", "Havelian", "Lora", "Nawanshahr"],
  Mardan: ["Mardan City", "Takht Bhai", "Katlang"],
  Swat: ["Mingora", "Kabal", "Matta", "Bahrain", "Khwazakhela", "Charbagh"],
  Dera_Ismail_Khan: ["Dera Ismail Khan City", "Kulachi", "Paroa", "Paharpur"],
  Bannu: ["Bannu City", "Domel", "Kaki"],
  Kohat: ["Kohat City", "Lachi", "Gumbat", "Shakardara"],
  Nowshera: ["Nowshera City", "Pabbi", "Jehangira", "Akora Khattak"],
  Charsadda: ["Charsadda City", "Tangi", "Shabqadar"],
  Mansehra: ["Mansehra City", "Balakot", "Oghi", "Darband"],
  Shangla: ["Shangla City", "Alpuri", "Puran", "Chakesar"],
  Batagram: ["Batagram City", "Allai", "Thakot"],
  Lower_Dir: ["Timergara", "Lal Qila", "Maidan", "Samar Bagh"],
  Upper_Dir: ["Dir City", "Barawal", "Wari", "Kumrat"],
  Hangu: ["Hangu City", "Thall", "Doaba"],
  Karak: ["Karak City", "Takht-e-Nasrati", "Banda Daud Shah"],
  Lakki_Marwat: ["Lakki Marwat City", "Sarai Naurang", "Ghoriwala"],
  Tank: ["Tank City", "Jandola", "Pezu"],
  Chitral: ["Chitral City", "Mastuj", "Drosh"],

  Jacobabad: ["Jacobabad City", "Thul", "Garhi Khairo"],
  Kashmore: ["Kashmore City", "Kandhkot", "Tangwani"],
  Larkano: ["Larkano City", "Ratodero", "Dokri", "Bakrani"],
  Kamber_Shahdadkot: [
    "Shahdadkot",
    "Kamber",
    "Miro Khan",
    "Warah",
    "Sijawal Junejo",
  ],
  Shikarpur: ["Shikarpur City", "Lakhi Ghulam Shah", "Khanpur", "Garhi Yasin"],
  Ghotki: ["Ghotki City", "Mirpur Mathelo", "Ubauro", "Khangarh", "Daharki"],
  Sukkur: ["Sukkur City", "Rohri", "Pano Akil", "Salehpat"],
  Khairpur: [
    "Khairpur City",
    "Kot Diji",
    "Gambat",
    "Sobhodero",
    "Kingri",
    "Faiz Ganj",
    "Thari Mirwah",
    "Nara",
  ],
  Naushero_Feroz: [
    "Naushero Feroz City",
    "Moro",
    "Bhiria",
    "Kandiaro",
    "Mehrabpur",
  ],
  Shaheed_Benazirabad: ["Nawabshah City", "Daur", "Sakrand", "Qazi Ahmad"],
  Sanghar: [
    "Sanghar City",
    "Tando Adam",
    "Shahdadpur",
    "Khipro",
    "Sinjhoro",
    "Jam Nawaz Ali",
  ],
  Mirpurkhas: ["Mirpurkhas City", "Digri", "Jhuddo", "Kot Ghulam Muhammad"],
  Umerkot: ["Umerkot City", "Samaro", "Kunri", "Pithoro"],
  Tharparkar: ["Mithi", "Nagarparkar", "Chachro", "Dahli", "Diplo", "Islamkot"],
  Dadu: ["Dadu City", "Mehar", "Khairpur Nathan Shah", "Johi"],
  Jamshoro: ["Jamshoro City", "Sehwan", "Kotri", "Manjhand"],
  Matiari: ["Matiari City", "Hala", "Saeedabad"],
  Hyderabad: ["Hyderabad City", "Qasimabad", "Latifabad", "Tando Jam"],
  Tando_Muhammad_Khan: [
    "Tando Muhammad Khan City",
    "Bulri Shah Karim",
    "Tando Ghulam Hyder",
  ],
  Tando_Allahyar: ["Tando Allahyar City", "Chambar", "Jhando Mari"],
  Badin: ["Badin City", "Tando Bago", "Talhar", "Matli", "Golarchi"],
  Sujawal: ["Sujawal City", "Jati", "Mirpur Bathoro", "Shah Bunder"],
  Thatta: ["Thatta City", "Mirpur Sakro", "Ghorabari", "Keti Bunder"],

  Karachi: [
    "Karachi South",
    "Karachi East",
    "Karachi West",
    "Malir",
    "Korangi",
    "Central",
    "Clifton",
  ],
};
